name: route_mates
description: Travel with your companions in convoys.
publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

# `flutter pub upgrade --major-versions`
# `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_database: ^10.2.7
  cloud_firestore: ^4.8.4
  cloud_functions: ^4.4.0
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.7.9
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.7.4
  google_sign_in: ^6.1.4
  image_picker: ^1.0.2
  image: ^4.1.3
  flutter_svg: ^2.0.7
  image_cropper: ^5.0.0
  get_time_ago: ^1.2.5
  assorted_layout_widgets: ^8.0.4
  uuid: ^3.0.7
  regexpattern: ^2.5.0
  provider: ^6.0.5
  go_router: ^12.1.1
  pinput: ^3.0.1
  mapbox_maps_flutter: ^0.5.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  screenshot: ^2.1.0
  flutter_background_service: ^5.0.4
  fluttertoast: ^8.2.4
  background_location: ^0.11.8
  flutter_local_notifications: ^16.3.0
  hive: ^2.2.3
  hive_flutter:
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.7
  google_mobile_ads: ^4.0.0
  fluttericon: ^2.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  vibration: ^1.8.4
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/svgs/
    - assets/pngs/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
        - asset: fonts/RobotoMono-Regular.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Regular.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
    - family: Quattrocento
      fonts:
        - asset: fonts/QuattrocentoSans-Bold.ttf
        - asset: fonts/QuattrocentoSans-Regular.ttf
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Black.otf
        - asset: fonts/Satoshi-BlackItalic.otf
        - asset: fonts/Satoshi-Bold.otf
        - asset: fonts/Satoshi-BoldItalic.otf
        - asset: fonts/Satoshi-Light.otf
        - asset: fonts/Satoshi-LightItalic.otf
        - asset: fonts/Satoshi-Medium.otf
        - asset: fonts/Satoshi-MediumItalic.otf
        - asset: fonts/Satoshi-Regular.otf
        - asset: fonts/Satoshi-Italic.otf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

flutter_native_splash:
  color: "#131316"

  android_12:
    icon_background_color: "#131316"
    color: "#131316"

  web: false
